
[package]
name = "r2r"
version = "0.0.4"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
description = "Minimal ros2 bindings."
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.5"
failure_derive = "0.1.5"
common = { path = "common", version = "0.0.1" }
rcl = { path = "rcl", version = "0.0.1" }
msg_gen = { path = "msg_gen", version = "0.0.1" }

[dev-dependencies]
serde_json = "1.0"

[build-dependencies]
common = { path = "common", version = "0.0.1" }
msg_gen = { path = "msg_gen", version = "0.0.1" }

[workspace]
