[package]
name = "r2r_rcl"
version = "0.2.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"
readme = "README.md"
homepage = "https://github.com/sequenceplanner/r2r"
repository = "https://github.com/sequenceplanner/r2r"
documentation = "https://sequenceplanner.github.io/r2r/"

[dependencies]
paste = "1.0.4"
widestring = "0.4.3"

[build-dependencies]
bindgen = "0.57.0"
itertools = "0.10.0"
r2r_common = { path = "../r2r_common", version = "0.2.0" }
