[package]
name = "msg_gen"
version = "0.0.1"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[features]
headers = []

[dependencies]
lazy_static = "1.3.0"
libc = "0.2.0"
rcl = { path = "../rcl", version = "0.0.1" }

[build-dependencies]
bindgen = "0.50.0"
rcl = { path = "../rcl", version = "0.0.1" }
common = { path = "../common", version = "0.0.1" }
heck = "0.3.1"
