name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing_rolling:
    runs-on: ubuntu-latest
    
    steps:
    - name: test
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: rolling
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - uses: actions/checkout@v2
    - run: cargo test --verbose
