name: Rust

on:
  push:
    branches: [ futures ]
  pull_request:
    branches: [ futures ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing_rolling:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile --tag r2r_test
    - run: docker run r2r_test
    
  testing_foxy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_foxy --tag r2r_test
    - run: docker run r2r_test

  testing_galactic:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_galactic --tag r2r_test
    - run: docker run r2r_test
