name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing_rolling:
    runs-on: ubuntu-latest
    container: kristoferb/spbase_ros2:rolling
    
    steps:
    - name: env test
      run: env
    - name: ros2 test
      run: ros2
    - name: rust test
      run: cargo
